version: "3.3"

services:
  db:
    image: andresvidal/rpi3-mongodb3:latest
    networks:
      - moviegobs
      - tvgobs
    ports:
      - 27017:27017
    # volumes:
    #   - mongovol:/data/db

  app:
    image: app:2.9
    build: ./app
    environment:
      - MOVIEGOBS_SETUP=1
      - MOVIEGOBS_MONGODB_ADDRESS=mongodb://db:27017/moviegobs
      - MOVIEGOBS_MONGODB_THUMB_ADDRESS=mongodb://db:27017/movbsthumb
      - MOVIEGOBS_MOVIES_PATH=/root/fsData/Movies
      - MOVIEGOBS_TVSHOWS_PATH=/root/fsData/TVShows
      - MOVIEGOBS_POSTERS_PATH=/root/fsData/Thumbs
      - MOVIEGOBS_HARDDRIVE_POSTERS_PATH=/root/fsData/Posters
      - MOVIEGOBS_NO_ART_PIC_PATH=./static/images/animals.jpg
      - MOVIEGOBS_THUMB_BASE_PATH=./static/images/thumbnails
      - MOVIEGOBS_THUMBNAIL_PIC_PATH=./static/images/thumbnails
      - MOVIEGOBS_TEMPLATE_ADDRESS=./static/templates/moviegobs.template
      - MOVIEGOBS_SERVER_PORT=8888
      - MOVIEGOBS_SERVER_ADDRESS=http://192.168.0.42
      - MOVIEGOBS_OMXPLAYER_ADDRESS=http://192.168.0.42:8181/OmxplayerPlayMedia
      - MOVIEGOBS_OMXPLAYER_ADDRESS_REACT=http://192.168.0.42:8181/OmxplayerPlayMediaReact
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    networks:
      - moviegobs
    ports:
      - 8888:8888
    volumes:
      - moviegobsvol:/root/fsData/
      - moviegobspicvol:/root/static/
    depends_on:
      - db

  tvapp:
    image: tvapp:2.6
    build: ./tvapp
    environment:
      - TVGOBS_SETUP=1
      - TVGOBS_MONGODB_ADDRESS=mongodb://db:27017/tvgobs
      - TVGOBS_MONGODB_THUMB_ADDRESS=mongodb://db:27017/tvbsthumb
      - TVGOBS_LOG=./logs/tvgobs_log.txt
      - TVGOBS_TVSHOWS_PATH=/root/fsData/TVShows
      - TVGOBS_HARDRIVE_TVPOSTER_PATH=/root/fsData/TVPosters
      - TVGOBS_NO_ART_PIC_PATH=./static/images/animals.jpg
      - TVGOBS_TEMPLATE_ADDRESS=./static/templates/tvgobs.template
      - TVGOBS_OMXPLAYER_ADDRESS=http://192.168.0.42:8181/OmxplayerPlayMediaReact
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    networks:
      - tvgobs
    ports:
      - 9999:9999
    volumes:
      - tvgobsvol:/root/fsData/
    depends_on:
      - db

networks:
  moviegobs:
  tvgobs:

volumes:
  mongovol:

  moviegobsvol:
    driver: local
    driver_opts:
      type: none
      device: /media/pi/PiTB/media
      o: bind

  moviegobspicvol:
    driver: local
    driver_opts:
      type: none
      device: /media/pi/PiTB/media/Thumbs
      o: bind


  tvgobsvol:
    driver: local
    driver_opts:
      type: none
      device: /media/pi/PiTB/media/TVShows
      o: bind
