apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/1/./kompose-linux-amd64 --file ./docker-compose.yml
      convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: tvapp
  name: tvapp
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: tvapp
    spec:
      containers:
      - env:
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: example
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: TVGOBS_LOG
          value: ./logs/tvgobs_log.txt
        - name: TVGOBS_MONGODB_ADDRESS
          value: mongodb://db:27017/tvgobs
        - name: TVGOBS_MONGODB_THUMB_ADDRESS
          value: mongodb://db:27017/tvbsthumb
        - name: TVGOBS_NO_ART_PIC_PATH
          value: ./static/images/animals.jpg
        - name: TVGOBS_OMXPLAYER_ADDRESS
          value: '"http://192.168.0.42"'
        - name: TVGOBS_SETUP
          value: "1"
        - name: TVGOBS_TEMPLATE_ADDRESS
          value: ./static/templates/tvgobs.template
        - name: TVGOBS_TVSHOWS_PATH
          value: ./fsData/media/TVShows
        image: tvapp
        name: tvapp
        ports:
        - containerPort: 9999
        resources: {}
        volumeMounts:
        - mountPath: /root/fsData
          name: tvgobsvol
      restartPolicy: Always
      volumes:
      - name: tvgobsvol
        persistentVolumeClaim:
          claimName: tvgobsvol
status: {}
